name: macshot
options:
  bundleIdPrefix: at.teibler
  deploymentTarget:
    macOS: "14.0"
targets:
  macshot:
    type: application
    platform: macOS
    sources:
      - macshot
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: at.teibler.macshot
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
        ENABLE_HARDENED_RUNTIME: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
        Release:
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: "Developer ID Application"
          DEVELOPMENT_TEAM: V8583J8736
    info:
      path: macshot/Info.plist
      properties:
        CFBundleDisplayName: macshot
        LSUIElement: true
